version: "3.7"

services:
  web:
    image: liwei2633/gopeed:latest
    container_name: gopeed_web_1
    restart: on-failure
    ports:
      - "9999:9999"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
    volumes:
      - ${APP_DATA_DIR}/data/storage:/app/storage

      - ${UMBREL_ROOT}/data/storage/downloads:/app/Downloads
